module.exports = {
"IERC165": require('./IERC165').default,
"Address": require('./Address').default,
"Counters": require('./Counters').default,
"ERC165": require('./ERC165').default,
"SafeMath": require('./SafeMath').default,
"IERC20": require('./IERC20').default,
"IERC721": require('./IERC721').default,
"IERC721Receiver": require('./IERC721Receiver').default,
"IERC721Enumerable": require('./IERC721Enumerable').default,
"IERC721Metadata": require('./IERC721Metadata').default,
"IERC721Full": require('./IERC721Full').default,
"ERC20": require('./ERC20').default,
"TToken": require('./TToken').default,
"ERC721": require('./ERC721').default,
"ERC721Metadata": require('./ERC721Metadata').default,
"ERC721Enumerable": require('./ERC721Enumerable').default,
"ERC721Full": require('./ERC721Full').default,
"Shintsha": require('./Shintsha').default,

};